-- Initial Supabase/Postgres schema for M6 Futebol Clube.
-- Mirrors the current SQLite/D1 model while preserving integer timestamps.

begin;

create table organizations (
  id text primary key,
  name text not null,
  slug text not null unique,
  created_at bigint not null
);

create table local_users (
  id text primary key,
  email text not null unique,
  display_name text not null,
  password_hash text not null,
  password_salt text not null,
  created_at bigint not null,
  updated_at bigint not null,
  username text unique,
  role text not null default 'admin'
);

create table organization_members (
  id bigint generated by default as identity primary key,
  organization_id text not null references organizations(id) on delete cascade,
  user_id text not null references local_users(id) on delete cascade,
  display_name text not null,
  role text not null default 'owner' check (role in ('owner','admin','coach','finance')),
  created_at bigint not null,
  unique (organization_id, user_id)
);

create index organization_members_user_idx on organization_members(user_id);

create table local_auth_sessions (
  token_hash text primary key,
  user_id text not null references local_users(id) on delete cascade,
  organization_id text not null references organizations(id) on delete cascade,
  expires_at bigint not null,
  created_at bigint not null
);

create index local_auth_sessions_user_idx on local_auth_sessions(user_id);
create index local_auth_sessions_organization_idx on local_auth_sessions(organization_id);

create table sports_categories (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  name text not null,
  sort_order integer not null default 0,
  active integer not null default 1,
  created_at bigint not null,
  updated_at bigint not null,
  unique (organization_id, name)
);

create index sports_categories_org_order_idx on sports_categories(organization_id, sort_order);

create table athletes (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  full_name text not null,
  birth_year integer not null,
  birth_date text,
  category text not null,
  guardian_name text not null,
  guardian_document text,
  guardian_phone text,
  guardian_email text,
  emergency_name text,
  emergency_phone text,
  allergies text,
  medications text,
  medical_notes text,
  image_authorized integer not null default 0,
  attendance_rate integer not null default 100,
  financial_status text not null default 'paid' check (financial_status in ('paid','pending')),
  qr_token text unique,
  active integer not null default 1,
  created_by text not null,
  created_at bigint not null,
  updated_at bigint not null
);

create index athletes_organization_idx on athletes(organization_id);
create index athletes_name_idx on athletes(organization_id, full_name);
create index athletes_category_idx on athletes(organization_id, category);

create table athlete_documents (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  object_key text not null unique,
  file_name text not null,
  content_type text not null,
  size_bytes integer not null,
  kind text not null default 'other' check (kind in ('identity','medical','authorization','other')),
  uploaded_by text not null,
  created_at bigint not null
);

create index athlete_documents_athlete_idx on athlete_documents(organization_id, athlete_id);

create table teams (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  name text not null,
  category text not null,
  coach_name text,
  schedule_days text not null default '[]',
  start_time text not null default '08:00',
  end_time text not null default '09:00',
  place text not null default 'Campo 1',
  capacity integer not null default 24,
  active integer not null default 1,
  created_at bigint not null
);

create index teams_organization_idx on teams(organization_id);

create table team_athletes (
  id bigint generated by default as identity primary key,
  organization_id text not null references organizations(id) on delete cascade,
  team_id text not null references teams(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  active integer not null default 1,
  enrolled_at bigint not null,
  unique (team_id, athlete_id)
);

create index team_athletes_organization_idx on team_athletes(organization_id);
create index team_athletes_athlete_idx on team_athletes(athlete_id);

create table attendance_sessions (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  team_id text not null references teams(id) on delete cascade,
  session_date text not null,
  recorded_by text not null,
  status text not null default 'completed' check (status in ('completed','canceled')),
  canceled_at bigint,
  canceled_by text,
  cancel_reason text,
  created_at bigint not null,
  unique (team_id, session_date)
);

create index attendance_sessions_organization_idx on attendance_sessions(organization_id);

create table attendance_records (
  id bigint generated by default as identity primary key,
  session_id text not null references attendance_sessions(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  present integer not null default 1,
  note text,
  unique (session_id, athlete_id)
);

create table athlete_check_ins (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  team_id text not null references teams(id) on delete cascade,
  attendance_session_id text not null references attendance_sessions(id) on delete cascade,
  scanned_at bigint not null,
  scanned_by text not null,
  guardian_phone text,
  notification_message text not null,
  notification_status text not null default 'pending' check (notification_status in ('pending','sent','failed','skipped')),
  notification_error text,
  notified_at bigint,
  unique (organization_id, athlete_id, team_id, attendance_session_id)
);

create index athlete_check_ins_org_date_idx on athlete_check_ins(organization_id, scanned_at);
create index athlete_check_ins_athlete_date_idx on athlete_check_ins(athlete_id, scanned_at);
create index athlete_check_ins_notification_idx on athlete_check_ins(organization_id, notification_status);

create table class_reminders (
  id bigint generated by default as identity primary key,
  organization_id text not null references organizations(id) on delete cascade,
  team_id text not null references teams(id) on delete cascade,
  session_date text not null,
  sent_at bigint not null,
  recipient_count integer not null default 0,
  unique (team_id, session_date)
);

create index class_reminders_organization_idx on class_reminders(organization_id);

create table athlete_evaluations (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  evaluation_date text not null,
  technical_score integer not null,
  physical_score integer not null,
  tactical_score integer not null,
  behavioral_score integer not null,
  strengths text,
  improvements text,
  next_goals text,
  evaluated_by text not null,
  created_at bigint not null,
  updated_at bigint not null
);

create index athlete_evaluations_organization_idx on athlete_evaluations(organization_id);
create index athlete_evaluations_athlete_date_idx on athlete_evaluations(athlete_id, evaluation_date);

create table training_sessions (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  team_id text not null references teams(id),
  title text not null,
  objective text not null,
  session_date text not null,
  duration_minutes integer not null,
  status text not null default 'planned' check (status in ('planned','completed','cancelled')),
  notes text,
  created_by text not null,
  created_at bigint not null,
  updated_at bigint not null
);

create index training_sessions_organization_date_idx on training_sessions(organization_id, session_date);
create index training_sessions_team_idx on training_sessions(team_id);

create table training_drills (
  id text primary key,
  session_id text not null references training_sessions(id) on delete cascade,
  position integer not null,
  name text not null,
  focus text,
  duration_minutes integer not null,
  description text
);

create index training_drills_session_position_idx on training_drills(session_id, position);

create table communications (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  title text not null,
  message text not null,
  audience_type text not null check (audience_type in ('all','team')),
  team_id text references teams(id),
  priority text not null default 'normal' check (priority in ('normal','important','urgent')),
  status text not null default 'draft' check (status in ('draft','scheduled','sent','cancelled')),
  scheduled_at text,
  sent_at bigint,
  created_by text not null,
  created_at bigint not null,
  updated_at bigint not null
);

create index communications_organization_status_idx on communications(organization_id, status);

create table communication_recipients (
  id text primary key,
  communication_id text not null references communications(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  guardian_name text not null,
  guardian_email text,
  guardian_phone text,
  read_at bigint,
  unique (communication_id, athlete_id)
);

create index communication_recipients_message_idx on communication_recipients(communication_id);

create table billing_plans (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  name text not null,
  amount_cents integer not null check (amount_cents > 0),
  due_day integer not null default 10,
  category text,
  active integer not null default 1,
  created_at bigint not null,
  updated_at bigint not null
);

create index billing_plans_organization_idx on billing_plans(organization_id);

create table athlete_billing (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  plan_id text not null references billing_plans(id),
  discount_type text not null default 'none' check (discount_type in ('none','fixed','percent')),
  discount_value integer not null default 0,
  custom_due_day integer,
  provider_customer_id text,
  active integer not null default 1,
  created_at bigint not null,
  updated_at bigint not null,
  unique (athlete_id)
);

create index athlete_billing_organization_idx on athlete_billing(organization_id);
create index athlete_billing_plan_idx on athlete_billing(plan_id);

create table billing_combos (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  name text not null,
  combo_type text not null default 'custom',
  duration_months integer not null,
  description text,
  base_plan_id text references billing_plans(id),
  base_amount_cents integer not null check (base_amount_cents > 0),
  discount_type text not null default 'none' check (discount_type in ('none','fixed','percent')),
  discount_value integer not null default 0,
  final_amount_cents integer not null check (final_amount_cents > 0),
  billing_mode text not null default 'installments' check (billing_mode in ('upfront','installments')),
  installment_count integer not null,
  active integer not null default 1,
  created_at bigint not null,
  updated_at bigint not null
);

create index billing_combos_organization_idx on billing_combos(organization_id);

create table athlete_combos (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  combo_id text not null references billing_combos(id),
  combo_name_snapshot text not null,
  duration_months integer not null,
  base_amount_cents integer not null,
  discount_type text not null,
  discount_value integer not null,
  final_amount_cents integer not null,
  installment_count integer not null,
  start_date text not null,
  end_date text not null,
  status text not null default 'active' check (status in ('active','completed','cancelled','expired')),
  created_at bigint not null,
  updated_at bigint not null,
  unique (athlete_id, start_date)
);

create index athlete_combos_organization_idx on athlete_combos(organization_id);
create index athlete_combos_athlete_idx on athlete_combos(athlete_id);

create table payments (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  athlete_combo_id text references athlete_combos(id),
  combo_installment_number integer,
  combo_installment_total integer,
  reference_month text not null,
  amount_cents integer not null check (amount_cents > 0),
  due_date text not null,
  paid_at bigint,
  paid_amount_cents integer default 0 check (coalesce(paid_amount_cents, 0) >= 0),
  payment_method text check (payment_method in ('cash','pix','card','bank','other')),
  plan_name text,
  notes text,
  external_provider text,
  external_payment_id text,
  invoice_url text,
  bank_slip_url text,
  external_status text,
  external_creation_status text check (external_creation_status in ('creating','created','failed','unknown')),
  external_creation_token text,
  external_creation_started_at bigint,
  updated_at bigint not null default 0,
  status text not null default 'open' check (status in ('open','paid','partial','overdue','cancelled')),
  created_at bigint not null,
  check (coalesce(paid_amount_cents, 0) <= amount_cents)
);

create unique index payments_athlete_month_unique on payments(organization_id, athlete_id, reference_month) where status <> 'cancelled';
create unique index payments_external_payment_unique on payments(external_payment_id) where external_payment_id is not null;
create index payments_organization_status_idx on payments(organization_id, status);

create table athlete_combo_installments (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_combo_id text not null references athlete_combos(id) on delete cascade,
  installment_number integer not null,
  installment_total integer not null,
  reference_month text not null,
  due_date text not null,
  amount_cents integer not null,
  payment_id text references payments(id),
  created_at bigint not null,
  unique (athlete_combo_id, installment_number)
);

create index athlete_combo_installments_organization_idx on athlete_combo_installments(organization_id);

create table athlete_combo_coverage (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  athlete_combo_id text not null references athlete_combos(id) on delete cascade,
  reference_month text not null,
  active integer not null default 1,
  created_at bigint not null,
  released_at bigint,
  unique (athlete_combo_id, reference_month)
);

create unique index athlete_combo_coverage_active_unique on athlete_combo_coverage(organization_id, athlete_id, reference_month) where active = 1;

create table athlete_billing_month_reservations (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  reference_month text not null,
  source_type text not null check (source_type in ('monthly','combo')),
  source_id text not null,
  created_at bigint not null,
  unique (organization_id, athlete_id, reference_month)
);

create index athlete_billing_month_reservation_source_idx on athlete_billing_month_reservations(source_type, source_id);

create table payment_transactions (
  id text primary key,
  payment_id text not null references payments(id) on delete cascade,
  type text not null check (type in ('payment','refund','opening_balance')),
  amount_cents integer not null check (amount_cents > 0),
  payment_method text check (payment_method in ('cash','pix','card','bank','other')),
  origin text not null check (origin in ('manual','asaas','migration','system')),
  occurred_at bigint not null,
  created_by text,
  external_transaction_id text,
  reverses_transaction_id text references payment_transactions(id) on delete restrict,
  idempotency_key text not null unique,
  note text,
  created_at bigint not null
);

create unique index payment_transactions_external_unique on payment_transactions(origin, external_transaction_id, type) where external_transaction_id is not null;
create index payment_transactions_payment_date_idx on payment_transactions(payment_id, occurred_at);
create index payment_transactions_reversal_idx on payment_transactions(reverses_transaction_id);

create table billing_notification_settings (
  organization_id text primary key references organizations(id) on delete cascade,
  enabled integer not null default 1,
  before_due_enabled integer not null default 1,
  before_due_days integer not null default 3,
  due_today_enabled integer not null default 1,
  overdue_enabled integer not null default 1,
  overdue_days integer not null default 5,
  updated_at bigint not null
);

create table billing_notifications (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  payment_id text not null references payments(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  type text not null check (type in ('before_due','due_today','overdue')),
  phone text not null,
  message text not null,
  status text not null check (status in ('sent','failed')),
  error text,
  sent_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  unique (payment_id, type)
);

create index billing_notifications_organization_status_idx on billing_notifications(organization_id, status);

create table notification_outbox (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  athlete_id text not null references athletes(id) on delete cascade,
  payment_id text references payments(id) on delete set null,
  team_id text references teams(id) on delete set null,
  legacy_notification_id text,
  original_notification_id text,
  event_type text not null check (event_type in ('before_due','due_today','overdue','enrollment','controlled_test')),
  idempotency_key text not null unique,
  phone text not null,
  message text not null,
  status text not null default 'pending' check (status in ('pending','processing','sent','failed','delivery_unknown','superseded')),
  attempt_count integer not null default 0,
  max_attempts integer not null default 3,
  next_attempt_at bigint,
  locked_at bigint,
  locked_until bigint,
  lock_token text,
  last_error text,
  sent_at bigint,
  provider_message_id text,
  last_attempt_origin text check (last_attempt_origin in ('startup','reconnect','automatic','verify_now','enrollment','controlled_test','manual')),
  manual_resend_count integer not null default 0,
  created_at bigint not null,
  updated_at bigint not null
);

create index notification_outbox_eligible_idx on notification_outbox(organization_id, status, next_attempt_at);
create index notification_outbox_original_idx on notification_outbox(original_notification_id);

create table notification_attempts (
  id text primary key,
  notification_id text not null references notification_outbox(id) on delete cascade,
  attempt_number integer not null,
  origin text not null,
  lock_token text not null unique,
  status text not null,
  error text,
  provider_message_id text,
  started_at bigint not null,
  finished_at bigint
);

create index notification_attempts_notification_idx on notification_attempts(notification_id, started_at);

create table expenses (
  id text primary key,
  organization_id text not null references organizations(id) on delete cascade,
  reference_month text not null,
  description text not null,
  category text not null,
  supplier text,
  amount_cents integer not null check (amount_cents > 0),
  due_date text not null,
  paid_at bigint,
  payment_method text check (payment_method in ('cash','pix','card','bank','other')),
  status text not null default 'open' check (status in ('open','paid','overdue','cancelled')),
  notes text,
  installment_group_id text,
  installment_number integer not null default 1,
  installment_count integer not null default 1,
  created_by text not null,
  created_at bigint not null,
  updated_at bigint not null
);

create index expenses_organization_month_idx on expenses(organization_id, reference_month);
create index expenses_organization_status_idx on expenses(organization_id, status);
create index expenses_installment_group_idx on expenses(organization_id, installment_group_id);

create table license_state (
  id text primary key,
  install_id text not null,
  expires_at bigint,
  grace_days integer not null default 3,
  last_seen_at bigint not null,
  last_issued_at bigint,
  used_nonces text not null default '[]',
  created_at bigint not null,
  updated_at bigint not null
);

commit;
